### PR TITLE
Don't reset values during data storage

### PR DESCRIPTION
**Pull request by cristofercruz**
Value resetting is happening twice, after data storage and during espprinter_loop. The reset during data storage causes screen updates to stop after write times start to increase (around 18-19 for me running esp at 80MHz).

Removed the reset from store data so it just happens during espprinter_loop instead.

### CODE REVIEW

**Comment by HerrZatacke** [comment]
This will only work if you manually print imagy-by-image, as the value reset is done only when the printer is idle after 500ms(line 210)
If instead you print via the batch-function (Select->Up->A->A->Right->A) and select multiple images the printing fails (#2).

**Comment by cristofercruz** [comment]
Somehow it works both ways for me. Maybe because I'm running at 80Mhz? The USB is fried on my d1 mini so can't flash it at the moment to test 160Mhz.

**Comment by HerrZatacke** [comment]
Have you tried printing at least 3 images in batch mode?
imo it's impossible to be functioning. (also it actually does not function for me)

**Comment by cristofercruz** [comment]
Hmm, works here even batch printing a full camera roll. I tested using gbp, gbc, and gba just in case. The only time I get error 2 is when the cable comes loose. There seems to be about 1 second "pause" in data transfer while the printing screen comes up; at least on my end, that brief pause seems to be enough to run the reset the values and update oled routines in espprinter_loop between prints.

**Comment by HerrZatacke** [comment]
So it seems your gameboy pauses for himself after each image, even in batch mode? Which type of gameboy are you using?

**Comment by cristofercruz** [comment]
Mainly pocket but also tried color and advance and all seem to behave the same way. The pause is brief maybe a second or so while the printing screen flashes. https://youtu.be/lv77aeKQii0

**Comment by HerrZatacke** [comment]
Ok. I can kind of confirm your observation.
When I compile for 80MHz, It seems to run without issues.

As visible in your video, you are actually hitting the "idle" counter in the loop(), because you can actually see the image-counter ticking up.

> "The reset during data storage causes screen updates to stop"

This is actually the "desired" behaviour, as writing to the screen may take too much time that the printing may fail.

Because of this, and also that the code would not run with a 160MHz clock, for now, I'd prefer to leave it as it is.

Still maybe I'll manage to get it running as desired with just signaling "busy" to the gameboy. And in that case, it should be possible to also keep the screen updates consistent.

**Comment by cristofercruz** [comment]
Sounds good!

**Pull request closed without merging**
